### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by dtaylor-530** [michael-damatov/shuriken#1]
Really like the concept just finding the instructions difficult to follow.  The section, Initialization, suggests including a main method - Is that right ? In a Wpf project i wouldn't know where to put it. Only without it  properties aren't 'observed'. Still learning. Regards

**Comment by michael-damatov** [comment]
Please take a look at the provided `Demo.Shuriken.Wpf` project.

**Comment by dtaylor-530** [comment]
Thanks and sorry - that was an obvious one to miss on my part.
Also the 'Program' file, "\shuriken-develop\Sources\Demo.Shuriken.Wpf\Program.cs",
seems to missing a using statement, "using Shuriken.Diagnostics;". Only the solution didn't build without it.
